// web/dashboard-next/src/app/shared/ui/avatar/z-avatar.component.ts
import { Component, computed, input } from '@angular/core';
import { NgpAvatar, NgpAvatarFallback, NgpAvatarImage } from 'ng-primitives/avatar';

@Component({
  selector: 'z-avatar',
  hostDirectives: [NgpAvatar],
  imports: [NgpAvatarFallback, NgpAvatarImage],
  host: {
    class:
      'relative inline-flex shrink-0 items-center justify-center overflow-hidden rounded-md bg-[var(--z-surface-warm)] text-sm font-semibold text-[var(--z-primary)]',
  },
  template: `
    @if (resolvedImage(); as image) {
      <img ngpAvatarImage class="size-full object-cover" [src]="image" [alt]="alt()" />
    }
    <span ngpAvatarFallback class="grid size-full place-items-center">{{ fallback() }}</span>
  `,
})
export class ZAvatarComponent {
  readonly image = input<string>();
  readonly fallback = input('');
  readonly alt = input('');
  protected readonly resolvedImage = computed(() => {
    const image = this.image();
    if (!image) return undefined;
    return image.startsWith('data:') ? image : `data:image/jpeg;base64,${image}`;
  });
}

// mobile/src/components/ui/z-avatar.tsx
import { Image, Text, View } from 'react-native';
import { avatarSrc } from '../../lib/avatar';

/**
 * Group/user avatar. Mobile counterpart of the web `z-avatar`
 * wrapper (web/dashboard-next/src/app/shared/ui/avatar/).
 * Shows the image when present, otherwise the fallback initials.
 */
export type ZAvatarShape = 'rounded' | 'circle';

export function ZAvatar({
  image,
  fallback = '',
  size = 36,
  shape = 'rounded',
  alt,
  testID,
}: {
  image?: string;
  fallback?: string;
  size?: number;
  shape?: ZAvatarShape;
  alt?: string;
  testID?: string;
}) {
  return (
    <View
      testID={testID}
      className={`items-center justify-center overflow-hidden bg-z-surface-warm ${
        shape === 'circle' ? 'rounded-full' : 'rounded-md'
      }`}
      style={{ width: size, height: size }}
    >
      {image ? (
        <Image
          source={{ uri: avatarSrc(image) }}
          accessibilityLabel={alt}
          style={{ width: size, height: size }}
        />
      ) : (
        <Text className="text-sm font-semibold text-z-primary">{fallback}</Text>
      )}
    </View>
  );
}
