// web/dashboard-next/src/app/shared/ui/badge/z-badge.component.ts
import { NgClass } from '@angular/common';
import { Component, computed, input } from '@angular/core';

type BadgeTone = 'neutral' | 'primary' | 'success' | 'warning' | 'danger';

@Component({
  selector: 'z-badge',
  imports: [NgClass],
  template: `<span [ngClass]="classes()"><ng-content /></span>`,
})
export class ZBadgeComponent {
  readonly tone = input<BadgeTone>('neutral');

  protected readonly classes = computed(() => [
    'inline-flex w-fit items-center rounded-md border px-2 py-1 text-xs font-semibold leading-none',
    this.toneClasses(),
  ]);

  private toneClasses(): string {
    switch (this.tone()) {
      case 'primary':
        return 'border-[var(--z-primary-soft)] bg-[var(--z-primary-soft)] text-[var(--z-primary-strong)]';
      case 'success':
        return 'border-green-200 bg-green-50 text-[var(--z-success)]';
      case 'warning':
        return 'border-amber-200 bg-amber-50 text-[var(--z-warning)]';
      case 'danger':
        return 'border-rose-200 bg-rose-50 text-[var(--z-danger)]';
      default:
        return 'border-[var(--z-border)] bg-white text-[var(--z-muted)]';
    }
  }
}

// mobile/src/components/ui/z-badge.tsx
import { Text, View } from 'react-native';

export type ZBadgeTone = 'neutral' | 'primary' | 'success' | 'warning' | 'danger';

const containerClasses: Record<ZBadgeTone, string> = {
  neutral: 'border-z-border bg-z-surface',
  primary: 'border-z-primary-soft bg-z-primary-soft',
  success: 'border-green-200 bg-green-50',
  warning: 'border-amber-200 bg-amber-50',
  danger: 'border-rose-200 bg-rose-50',
};

const labelClasses: Record<ZBadgeTone, string> = {
  neutral: 'text-z-muted',
  primary: 'text-z-primary-strong',
  success: 'text-z-success',
  warning: 'text-z-warning',
  danger: 'text-z-danger',
};

/**
 * Status pill / count badge. Mobile counterpart of the web `z-badge`
 * wrapper (web/dashboard-next/src/app/shared/ui/badge/).
 */
export function ZBadge({
  label,
  tone = 'neutral',
  testID,
}: {
  label: string;
  tone?: ZBadgeTone;
  testID?: string;
}) {
  return (
    <View
      testID={testID}
      className={`self-start rounded-md border px-2 py-1 ${containerClasses[tone]}`}
    >
      <Text className={`text-xs font-semibold ${labelClasses[tone]}`}>{label}</Text>
    </View>
  );
}
