// web/dashboard-next/src/app/shared/ui/button/z-button.component.ts
import { NgClass } from '@angular/common';
import { Component, computed, input, output } from '@angular/core';
import { NgpButton } from 'ng-primitives/button';

type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
type ButtonSize = 'sm' | 'md';

@Component({
  selector: 'z-button',
  imports: [NgClass, NgpButton],
  template: `
    <button
      ngpButton
      [type]="type()"
      [disabled]="disabled()"
      [ngClass]="classes()"
      (click)="pressed.emit()"
    >
      <ng-content />
    </button>
  `,
})
export class ZButtonComponent {
  readonly variant = input<ButtonVariant>('primary');
  readonly size = input<ButtonSize>('md');
  readonly type = input<'button' | 'submit' | 'reset'>('button');
  readonly disabled = input(false);
  readonly pressed = output<void>();

  protected readonly classes = computed(() => [
    'inline-flex items-center justify-center gap-2 rounded-md border font-semibold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
    this.size() === 'sm' ? 'min-h-9 px-3 text-sm' : 'min-h-11 px-4 text-sm',
    this.variantClasses(),
  ]);

  private variantClasses(): string {
    switch (this.variant()) {
      case 'secondary':
        return 'border-[var(--z-border)] bg-white text-[var(--z-text)] hover:bg-[var(--z-surface-warm)] focus-visible:outline-[var(--z-primary)]';
      case 'ghost':
        return 'border-transparent bg-transparent text-[var(--z-muted)] hover:bg-[var(--z-surface-warm)] hover:text-[var(--z-text)] focus-visible:outline-[var(--z-primary)]';
      case 'danger':
        return 'border-rose-700 bg-rose-700 text-white hover:bg-rose-800 focus-visible:outline-rose-700';
      default:
        return 'border-[var(--z-primary)] bg-[var(--z-primary)] text-white hover:bg-[var(--z-primary-strong)] focus-visible:outline-[var(--z-primary)]';
    }
  }
}

// mobile/src/components/ui/z-button.tsx
import { Pressable, Text } from 'react-native';

export type ZButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';

const containerClasses: Record<ZButtonVariant, string> = {
  primary: 'bg-z-primary active:bg-z-primary-strong',
  secondary: 'bg-z-surface border border-z-border active:bg-z-surface-warm',
  ghost: 'bg-transparent active:bg-z-surface-muted',
  danger: 'bg-z-danger active:opacity-90',
};

const labelClasses: Record<ZButtonVariant, string> = {
  primary: 'text-white',
  secondary: 'text-z-text',
  ghost: 'text-z-text',
  danger: 'text-white',
};

export function ZButton({
  label,
  onPress,
  variant = 'primary',
  disabled = false,
}: {
  label: string;
  onPress?: () => void;
  variant?: ZButtonVariant;
  disabled?: boolean;
}) {
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityLabel={label}
      accessibilityState={{ disabled }}
      disabled={disabled}
      onPress={onPress}
      className={`items-center justify-center rounded-lg px-4 py-3 ${containerClasses[variant]} ${disabled ? 'opacity-50' : ''}`}
    >
      <Text className={`text-base font-semibold ${labelClasses[variant]}`}>{label}</Text>
    </Pressable>
  );
}
