// web/dashboard-next/src/app/shared/ui/empty-state/z-empty-state.component.ts
import { Component, input } from '@angular/core';
import { LucideInbox } from '@lucide/angular';

@Component({
  selector: 'z-empty-state',
  imports: [LucideInbox],
  template: `
    <section
      class="grid place-items-center rounded-lg border border-dashed border-[var(--z-border)] bg-[var(--z-surface)] px-5 py-8 text-center"
    >
      <div class="max-w-sm">
        <span
          class="mx-auto grid size-12 place-items-center rounded-lg bg-[var(--z-surface-warm)] text-[var(--z-primary)]"
        >
          <svg lucideInbox class="size-6" aria-hidden="true"></svg>
        </span>
        <h2 class="mt-4 text-base font-semibold">{{ title() }}</h2>
        <p class="mt-2 text-sm leading-6 text-[var(--z-muted)]">{{ description() }}</p>
        <div class="mt-5">
          <ng-content />
        </div>
      </div>
    </section>
  `,
})
export class ZEmptyStateComponent {
  readonly title = input.required<string>();
  readonly description = input.required<string>();
}

// mobile/src/components/ui/z-empty-state.tsx
import type { ReactNode } from 'react';
import { Text, View } from 'react-native';
import { Inbox } from 'lucide-react-native';
import { colors } from '../../theme/colors';

/**
 * Empty placeholder for lists and sections. Mobile counterpart of the web
 * `z-empty-state` wrapper (web/dashboard-next/src/app/shared/ui/empty-state/).
 * Optional children render as an action slot below the description.
 */
export function ZEmptyState({
  title,
  description,
  children,
}: {
  title: string;
  description: string;
  children?: ReactNode;
}) {
  return (
    <View className="items-center rounded-lg border border-dashed border-z-border bg-z-surface px-5 py-8">
      <View className="h-12 w-12 items-center justify-center rounded-lg bg-z-surface-warm">
        <Inbox color={colors.primary} size={24} />
      </View>
      <Text className="mt-4 text-base font-semibold text-z-text text-center">{title}</Text>
      <Text className="mt-2 text-sm leading-6 text-z-muted text-center">{description}</Text>
      {children ? <View className="mt-5">{children}</View> : null}
    </View>
  );
}
